// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tsflchdtmzqaavrwidoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzZmxjaGR0bXpxYWF2cndpZG9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MTQ0MTksImV4cCI6MjA2MDA5MDQxOX0.xF-FlmaVyb4G3g7hVSVMoofRzdrB7NQf3d2c0xXZVkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);